server:
  host: "0.0.0.0"
  port: "50051"

log_level: "info"

database:
  host: "postgres"
  port: 5432
  username: "postgres"
  password: "postgres"
  database: "gen_db"

jwt:
  access_secret: "gen"
  refresh_secret: "gen"
  access_ttl: "15m"
  refresh_ttl: "168h"

data_dir: "./data"

# mcp:
#   http_allow_any: false
#   http_allow_hosts:
#     - "0.0.0.0"

# attachment_hydrate_parallelism: 16 # Параллельная подготовка вложений в истории для LLM (1...64). 0 = 8
