import 'package:gen/domain/usecases/auth/change_password_usecase.dart';
import 'package:gen/domain/usecases/auth/login_usecase.dart';
import 'package:gen/domain/usecases/auth/logout_usecase.dart';
import 'package:gen/domain/usecases/auth/refresh_token_usecase.dart';
import 'package:gen/domain/usecases/chat/continue_assistant_usecase.dart';
import 'package:gen/domain/usecases/chat/connect_usecase.dart';
import 'package:gen/domain/usecases/chat/create_session_usecase.dart';
import 'package:gen/domain/usecases/chat/delete_session_usecase.dart';
import 'package:gen/domain/usecases/chat/edit_user_message_and_continue_usecase.dart';
import 'package:gen/domain/usecases/chat/get_selected_runner_usecase.dart';
import 'package:gen/domain/usecases/chat/get_file_ingestion_status_usecase.dart';
import 'package:gen/domain/usecases/chat/get_session_file_usecase.dart';
import 'package:gen/domain/usecases/chat/get_session_messages_usecase.dart';
import 'package:gen/domain/usecases/chat/get_assistant_message_regenerations_usecase.dart';
import 'package:gen/domain/usecases/chat/get_session_messages_for_assistant_message_version_usecase.dart';
import 'package:gen/domain/usecases/chat/get_session_messages_for_user_message_version_usecase.dart';
import 'package:gen/domain/usecases/chat/put_session_file_usecase.dart';
import 'package:gen/domain/usecases/chat/get_session_settings_usecase.dart';
import 'package:gen/domain/usecases/chat/get_sessions_usecase.dart';
import 'package:gen/domain/usecases/chat/get_user_message_edits_usecase.dart';
import 'package:gen/domain/usecases/chat/regenerate_assistant_usecase.dart';
import 'package:gen/domain/usecases/chat/send_message_usecase.dart';
import 'package:gen/domain/usecases/chat/set_selected_runner_usecase.dart';
import 'package:gen/domain/usecases/chat/update_session_settings_usecase.dart';
import 'package:gen/domain/usecases/chat/update_session_title_usecase.dart';
import 'package:gen/domain/usecases/editor/transform_text_usecase.dart';
import 'package:gen/domain/usecases/runners/create_runner_usecase.dart';
import 'package:gen/domain/usecases/runners/delete_runner_usecase.dart';
import 'package:gen/domain/usecases/runners/get_runners_status_usecase.dart';
import 'package:gen/domain/usecases/runners/get_runners_usecase.dart';
import 'package:gen/domain/usecases/runners/get_user_runners_usecase.dart';
import 'package:gen/domain/usecases/runners/get_web_search_availability_usecase.dart';
import 'package:gen/domain/usecases/runners/update_runner_usecase.dart';
import 'package:gen/domain/usecases/users/create_user_usecase.dart';
import 'package:gen/domain/usecases/users/edit_user_usecase.dart';
import 'package:gen/domain/usecases/users/get_users_usecase.dart';
import 'package:get_it/get_it.dart';

void registerUseCasesModule(GetIt sl) {
  sl.registerFactory(() => ConnectUseCase(sl()));
  sl.registerFactory(() => SendMessageUseCase(sl()));
  sl.registerFactory(() => RegenerateAssistantUseCase(sl()));
  sl.registerFactory(() => ContinueAssistantUseCase(sl()));
  sl.registerFactory(() => EditUserMessageAndContinueUseCase(sl()));
  sl.registerFactory(() => GetUserMessageEditsUseCase(sl()));
  sl.registerFactory(() => CreateSessionUseCase(sl()));
  sl.registerFactory(() => GetSessionsUseCase(sl()));
  sl.registerFactory(() => GetSessionMessagesUseCase(sl()));
  sl.registerFactory(() => GetAssistantMessageRegenerationsUseCase(sl()));
  sl.registerFactory(() => GetSessionMessagesForUserMessageVersionUseCase(sl()));
  sl.registerFactory(() => GetSessionMessagesForAssistantMessageVersionUseCase(sl()));
  sl.registerFactory(() => GetSessionSettingsUseCase(sl()));
  sl.registerFactory(() => UpdateSessionSettingsUseCase(sl()));
  sl.registerFactory(() => GetSelectedRunnerUseCase(sl()));
  sl.registerFactory(() => SetSelectedRunnerUseCase(sl()));
  sl.registerFactory(() => DeleteSessionUseCase(sl()));
  sl.registerFactory(() => PutSessionFileUseCase(sl()));
  sl.registerFactory(() => GetFileIngestionStatusUseCase(sl()));
  sl.registerFactory(() => GetSessionFileUseCase(sl()));
  sl.registerFactory(() => UpdateSessionTitleUseCase(sl()));
  sl.registerFactory(() => TransformTextUseCase(sl()));
  sl.registerFactory(() => GetRunnersUseCase(sl()));
  sl.registerFactory(() => GetUserRunnersUseCase(sl()));
  sl.registerFactory(() => CreateRunnerUseCase(sl()));
  sl.registerFactory(() => UpdateRunnerUseCase(sl()));
  sl.registerFactory(() => DeleteRunnerUseCase(sl()));
  sl.registerFactory(() => GetRunnersStatusUseCase(sl()));
  sl.registerFactory(() => GetWebSearchAvailabilityUseCase(sl()));

  sl.registerFactory(() => LoginUseCase(sl()));
  sl.registerFactory(() => RefreshTokenUseCase(sl()));
  sl.registerFactory(() => LogoutUseCase(sl()));
  sl.registerFactory(() => ChangePasswordUseCase(sl()));

  sl.registerFactory(() => GetUsersUseCase(sl()));
  sl.registerFactory(() => CreateUserUseCase(sl()));
  sl.registerFactory(() => EditUserUseCase(sl()));
}
